CREATE DATABASE REPLACE_ME_DB_NAME;

DROP TABLE IF EXISTS REPLACE_ME_DB_NAME.REPLACE_ME_TABLE_NAME;

CREATE TABLE REPLACE_ME_DB_NAME.REPLACE_ME_TABLE_NAME (
    "Name" VARCHAR(12),
    "Age" VARCHAR(3),
    "Email_Address" VARCHAR(22),
    "Phone_Number" VARCHAR(9),
    "Date_of_Birth" VARCHAR(11),
    "Salary" VARCHAR(6)
);