#!/usr/bin/env python3
"""
PostgreSQL CSV Import Script - Generated by CSViper

This script imports CSV data into a PostgreSQL database using pre-generated SQL scripts.

Original CSV: test_data.csv
Generated on: 2025-06-29 00:46:39
"""

import os
import sys
import click

# Import the shared functionality from csviper package
try:
    from csviper.import_executor import ImportExecutor
except ImportError:
    # Fallback for standalone scripts - add the parent directory to path
    import sys
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))
    from csviper.import_executor import ImportExecutor


@click.command()
@click.option('--env_file_location', type=click.Path(),
              help='Path to .env file (auto-detected if not specified)')
@click.option('--csv_file', required=True, type=click.Path(),
              help='Path to CSV file to import')
@click.option('--db_schema_name', required=False,
              help='Database schema name (can be set via DB_SCHEMA env var)')
@click.option('--table_name', required=False,
              help='Table name for the imported data (can be set via DB_TABLE env var)')
@click.option('--trample', is_flag=True, default=False,
              help='Overwrite existing table data')
def main(env_file_location, csv_file, db_schema_name, table_name, trample):
    """
    Import CSV data into PostgreSQL database using pre-generated SQL scripts.
    
    This script was generated by CSViper for the CSV file: test_data.csv
    """
    try:
        # Load and validate configuration
        try:
            db_config, db_schema_name, table_name, metadata, encoding = ImportExecutor.load_and_validate_config(
                env_file_location, csv_file, db_schema_name, table_name, 'test_data.metadata.json'
            )
        except ValueError as e:
            if "too many values to unpack" in str(e):
                from csviper.exceptions import ImportExecutionError
                raise ImportExecutionError(
                    "Configuration loading failed due to version mismatch. "
                    "This error typically occurs when the import script expects a different number of return values "
                    "from the configuration loader. Please regenerate the import scripts.",
                    script_type="PostgreSQL",
                    original_error=e
                )
            else:
                raise
        except Exception as e:
            from csviper.exceptions import ImportExecutionError
            raise ImportExecutionError(
                f"Failed to load and validate configuration: {str(e)}",
                script_type="PostgreSQL",
                original_error=e
            )
        
        # Validate CSV header with proper encoding
        try:
            expected_columns = metadata['original_column_names']
            ImportExecutor.validate_csv_header(csv_file, expected_columns, encoding)
        except Exception as e:
            from csviper.exceptions import ImportExecutionError
            raise ImportExecutionError(
                f"CSV header validation failed: {str(e)}",
                script_type="PostgreSQL",
                original_error=e
            )
        
        # Check debug mode
        debug_mode = db_config.get('DEBUG', '').lower() in ('true', '1', 'yes', 'on')
        if debug_mode:
            click.echo("Debug mode enabled")
        
        click.echo(f"Importing {os.path.basename(csv_file)} into PostgreSQL database")
        click.echo(f"Schema: {db_schema_name}, Table: {table_name}")
        
        if trample:
            click.echo("Warning: --trample flag is set. Existing table data will be overwritten.")
        
        # Execute PostgreSQL import using the shared executor
        ImportExecutor.execute_postgresql_import(
            db_config, db_schema_name, table_name, csv_file, trample, 
            'test_data.create_table_postgres.sql'
        )
        
        click.echo("✓ PostgreSQL import completed successfully!")
        
    except Exception as e:
        from csviper.import_executor import Colors
        click.echo(Colors.dark_red(f"Error: {e}"), err=True)
        sys.exit(1)


if __name__ == '__main__':
    main()
