CREATE DATABASE IF NOT EXISTS REPLACE_ME_DB_NAME;

DROP TABLE IF EXISTS REPLACE_ME_DB_NAME.REPLACE_ME_TABLE_NAME;

CREATE TABLE REPLACE_ME_DB_NAME.REPLACE_ME_TABLE_NAME (
    `name` VARCHAR(12),
    `age` VARCHAR(3),
    `email_address` VARCHAR(22),
    `phone_number` VARCHAR(9),
    `date_of_birth` VARCHAR(11),
    `salary` VARCHAR(6)
);